language: php
php:
    - 7.1
before_install:
    - printf "\n" | pecl install imagick
install:
    - composer install
script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit
after_success:
  - travis_retry ./vendor/bin/coveralls